stages:
  - name: physics
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        inputfile: /home/irina/Projects/workflows/workflow-madminer/workflow-all/inputs/input_physics.yml
      workflow: {$ref: 'workflow_physics.yml'}