stages:
- name: sampling
  dependencies: [init]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      sampleworkdir: '{workdir}'
      combined_file: {step: init, output: combinedfile}
      input_file: {step: init, output: inputfile}
      n_trainsamples: {step: init, output: ntrainsamples}
      outputfile: '{workdir}/outputfile.txt'
    step: {$ref: 'workflow-ml/steps.yml#/sampling'}

- name: training
  dependencies: [sampling]
  scheduler:
    scheduler_type: multistep-stage
    parameters:
      trainworkdir: '{workdir}'
      input_file: {step: init, output: inputfile}
      trainfolder: {step: 'sampling', output: sampling_file, unwrap: true}
      trained_file: '{workdir}/trained_model.tar.gz'
    scatter:
      method: zip
      parameters: [trainfolder]
    step: {$ref: 'steps.yml#/training'}

