stages:
  - name: physics_simulations
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        inputfile: {step: init, output: inputfile}
        njobs: {step: init, output: njobs}
        inputdelphes: {step: init, output: inputdelphes}        
      workflow: {$ref: 'workflow_physics.yml'}